## Default Elasticsearch configuration from Elasticsearch base image.
## https://github.com/elastic/elasticsearch/blob/master/distribution/docker/src/docker/config/elasticsearch.yml
#
cluster.name: "es-docker-cluster"
network.host: 0.0.0.0
# bootstrap.memory_lock: false
# bootstrap.system_call_filter: false

## X-Pack settings

xpack.license.self_generated.type: basic


xpack.monitoring.collection.enabled: true

# 加密节点间通信-每个节点容器都要添加
xpack.security.enabled: true
xpack.security.transport.ssl.enabled: true
xpack.security.transport.ssl.verification_mode: certificate   #只验证证书是否受信任，不执行主机名验证。还可以设置成 full(还要验证主机名)、none(不验证证书)
xpack.security.transport.ssl.keystore.path: es-cluster.p12    #指定证书
xpack.security.transport.ssl.truststore.path: es-cluster.p12    #将密钥存储库也用做信任存储库

# 加密http通信-每个节点容器都要添加
xpack.security.http.ssl.enabled: true
xpack.security.http.ssl.verification_mode: certificate
xpack.security.http.ssl.keystore.path: es-cluster.p12   #指定使用的证书
xpack.security.http.ssl.truststore.path: es-cluster.p12   #密钥存储库包含CA证书,因此也可以用作信任存储库
