version: '3.2'

services:
  es01:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    container_name: es01
    hostname: es01
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./elasticsearch/config/es-cluster.p12:/usr/share/elasticsearch/config/es-cluster.p12:ro
      - /elk/elasticsearch/data/es01:/usr/share/elasticsearch/data:rw
    ports:
      - "9200:9200"
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ELASTIC_PASSWORD=admin#123
      - TZ=Asia/Shanghai 
    ulimits: 
      memlock: 
        soft: -1
        hard: -1
    networks:
      - elk

  es02:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    container_name: es02
    hostname: es02
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./elasticsearch/config/es-cluster.p12:/usr/share/elasticsearch/config/es-cluster.p12:ro
      - /elk/elasticsearch/data/es02:/usr/share/elasticsearch/data:rw
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ELASTIC_PASSWORD=admin#123
      - TZ=Asia/Shanghai 
    ulimits: 
      memlock: 
        soft: -1
        hard: -1
    networks:
      - elk
  
  es03:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    container_name: es03
    hostname: es03
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./elasticsearch/config/es-cluster.p12:/usr/share/elasticsearch/config/es-cluster.p12:ro
      - /elk/elasticsearch/data/es03:/usr/share/elasticsearch/data:rw
    environment:
      - node.name=es03
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ELASTIC_PASSWORD=admin#123
      - TZ=Asia/Shanghai 
    ulimits: 
      memlock: 
        soft: -1
        hard: -1
    networks:
      - elk

  lst01:
    build:
      context: logstash/
      args:
        ELK_VERSION: $ELK_VERSION
    container_name: lst01
    hostname: lst01
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/config/lst01.p12:/usr/share/logstash/config/lst01.p12:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:rw
    ports:
      - "514:5000/tcp"
      - "514:5000/udp"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx512m -Xms512m"
      TZ: Asia/Shanghai 
    networks:
      - elk
    depends_on:
      - es01
      - es02
      - es03

  kib01:
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    container_name: kib01
    hostname: kib01
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
      - ./kibana/config/kib01.p12:/usr/share/kibana/config/kib01.p12:ro
    ports:
      - "5600:5601"
    environment: 
      - TZ=Asia/Shanghai
    networks:
      - elk
    depends_on:
      - es01
      - es02
      - es03

networks:
  elk:
    driver: bridge
